// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32_S3_7inch_UI

#ifndef _ESP32_S3_7INCH_UI_UI_H
#define _ESP32_S3_7INCH_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_2043791660);   // assets/837189-200.png
LV_IMG_DECLARE( ui_img_195482244);   // assets/black-music-note-icon-6.png
LV_IMG_DECLARE( ui_img_swap_png);   // assets/swap.png
LV_IMG_DECLARE( ui_img_1842574513);   // assets/crab(1).png
LV_IMG_DECLARE( ui_img_closesmall3_png);   // assets/closesmall3.png
LV_IMG_DECLARE( ui_img_opensmall3_png);   // assets/opensmall3.png
LV_IMG_DECLARE( ui_img_malogo_png);   // assets/malogo.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
