// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32_S3_7inch_UI

#include "ui.h"

void ui_comp_Joint2_create_hook( lv_obj_t * comp)
{
}
