// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32_S3_7inch_UI

#ifndef _UI_COMP_JOINT2_H
#define _UI_COMP_JOINT2_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Joint2
#define UI_COMP_JOINT2_JOINT2 0
#define _UI_COMP_JOINT2_NUM 1
lv_obj_t *ui_Joint2_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
