// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32_S3_7inch_UI

#include "ui.h"

lv_obj_t *uic_arm_open;
lv_obj_t *uic_arm_close;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Action1 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Action2 = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Action3 = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_Action4 = NULL;lv_obj_t *ui_Image4 = NULL;lv_obj_t *ui_arm_close = NULL;lv_obj_t *ui_arm_open = NULL;lv_obj_t *ui_Button1 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Image5 = NULL;lv_obj_t *ui_ShutdownBtn = NULL;

static lv_timer_t *gripper_btn_timer = NULL;

static void gripper_btn_enable_timer_cb(lv_timer_t *timer) {
    lv_obj_clear_state(ui_Button1, LV_STATE_DISABLED);
    lv_timer_del(timer);
    gripper_btn_timer = NULL;
}

// event funtions
void ui_event_Action1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      action1_event( e );
}
}

void ui_event_Action2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      action2_event( e );
}
}

void ui_event_Action3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      action3_event( e );
}
}

void ui_event_Action4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      action4_event( e );
}
}

void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED ) {
    if (!lv_obj_has_state(target, LV_STATE_DISABLED)) {
        lv_obj_add_state(target, LV_STATE_DISABLED);
        if (gripper_btn_timer != NULL) {
            lv_timer_del(gripper_btn_timer);
        }
        gripper_btn_timer = lv_timer_create(gripper_btn_enable_timer_cb, 3000, NULL);
    }
}

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_arm_open, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_arm_close, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      open_gripper( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_arm_close, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_arm_open, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      close_gripper( e );
}
}

static void ui_event_ShutdownBtn(lv_event_t *e) {
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        shutdown_event(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 350);
lv_obj_set_height( ui_Panel1, 450);
lv_obj_set_x( ui_Panel1, -209 );
lv_obj_set_y( ui_Panel1, 0 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Action1 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Action1, 150);
lv_obj_set_height( ui_Action1, 200);
lv_obj_set_x( ui_Action1, -85 );
lv_obj_set_y( ui_Action1, -110 );
lv_obj_set_align( ui_Action1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Action1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Action1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Action1);
lv_img_set_src(ui_Image1, &ui_img_2043791660);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Image1,-100);
lv_img_set_zoom(ui_Image1,100);
lv_obj_set_style_img_recolor(ui_Image1, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Action2 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Action2, 150);
lv_obj_set_height( ui_Action2, 200);
lv_obj_set_x( ui_Action2, 85 );
lv_obj_set_y( ui_Action2, -110 );
lv_obj_set_align( ui_Action2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Action2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Action2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_Action2);
lv_img_set_src(ui_Image2, &ui_img_195482244);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,90);
lv_obj_set_style_img_recolor(ui_Image2, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Action3 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Action3, 150);
lv_obj_set_height( ui_Action3, 200);
lv_obj_set_x( ui_Action3, -85 );
lv_obj_set_y( ui_Action3, 110 );
lv_obj_set_align( ui_Action3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Action3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Action3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image3 = lv_img_create(ui_Action3);
lv_img_set_src(ui_Image3, &ui_img_swap_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image3,250);
lv_obj_set_style_img_recolor(ui_Image3, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Action4 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Action4, 150);
lv_obj_set_height( ui_Action4, 200);
lv_obj_set_x( ui_Action4, 85 );
lv_obj_set_y( ui_Action4, 110 );
lv_obj_set_align( ui_Action4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Action4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Action4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image4 = lv_img_create(ui_Action4);
lv_img_set_src(ui_Image4, &ui_img_1842574513);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image4,110);
lv_obj_set_style_img_recolor(ui_Image4, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_arm_close = lv_img_create(ui_Screen1);
lv_img_set_src(ui_arm_close, &ui_img_closesmall3_png);
lv_obj_set_width( ui_arm_close, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_arm_close, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_arm_close, 180 );
lv_obj_set_y( ui_arm_close, 77 );
lv_obj_set_align( ui_arm_close, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_arm_close, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_arm_close, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_arm_close,600);

ui_arm_open = lv_img_create(ui_Screen1);
lv_img_set_src(ui_arm_open, &ui_img_opensmall3_png);
lv_obj_set_width( ui_arm_open, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_arm_open, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_arm_open, 181 );
lv_obj_set_y( ui_arm_open, 3 );
lv_obj_set_align( ui_arm_open, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_arm_open, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_arm_open, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_arm_open,700);

ui_Button1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 169);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_x( ui_Button1, 184 );
lv_obj_set_y( ui_Button1, 184 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Toggle Gripper");

ui_Image5 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image5, &ui_img_malogo_png);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image5, 345 );
lv_obj_set_y( ui_Image5, -190 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image5,200);
lv_obj_set_style_radius(ui_Image5, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Image5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Image5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ShutdownBtn = lv_btn_create(ui_Screen1);
lv_obj_set_width(ui_ShutdownBtn, 55);
lv_obj_set_height(ui_ShutdownBtn, 35);
lv_obj_set_align(ui_ShutdownBtn, LV_ALIGN_BOTTOM_RIGHT);
lv_obj_set_x(ui_ShutdownBtn, -10);
lv_obj_set_y(ui_ShutdownBtn, -10);
lv_obj_clear_flag(ui_ShutdownBtn, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_bg_color(ui_ShutdownBtn, lv_color_hex(0x441111), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_ShutdownBtn, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ShutdownBtn, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
{
    lv_obj_t *lbl = lv_label_create(ui_ShutdownBtn);
    lv_label_set_text(lbl, LV_SYMBOL_POWER);
    lv_obj_set_align(lbl, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(lbl, lv_color_hex(0xFF6666), LV_PART_MAIN | LV_STATE_DEFAULT);
}
lv_obj_add_event_cb(ui_ShutdownBtn, ui_event_ShutdownBtn, LV_EVENT_ALL, NULL);

lv_obj_add_event_cb(ui_Action1, ui_event_Action1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Action2, ui_event_Action2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Action3, ui_event_Action3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Action4, ui_event_Action4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
uic_arm_close = ui_arm_close;
uic_arm_open = ui_arm_open;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Panel1= NULL;
ui_Action1= NULL;
ui_Image1= NULL;
ui_Action2= NULL;
ui_Image2= NULL;
ui_Action3= NULL;
ui_Image3= NULL;
ui_Action4= NULL;
ui_Image4= NULL;
uic_arm_close= NULL;
ui_arm_close= NULL;
uic_arm_open= NULL;
ui_arm_open= NULL;
ui_Button1= NULL;
ui_Label1= NULL;
ui_Image5= NULL;
ui_ShutdownBtn= NULL;

}
