// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32_S3_7inch_UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void action1_event(lv_event_t * e);
void action2_event(lv_event_t * e);
void action3_event(lv_event_t * e);
void action4_event(lv_event_t * e);
void open_gripper(lv_event_t * e);
void close_gripper(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
