// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32_S3_7inch_UI

#include "ui.h"

// COMPONENT Joint2

lv_obj_t *ui_Joint2_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Joint2;
cui_Joint2 = lv_arc_create(comp_parent);
lv_obj_set_width( cui_Joint2, 150);
lv_obj_set_height( cui_Joint2, 150);
lv_obj_set_x( cui_Joint2, -87 );
lv_obj_set_y( cui_Joint2, 57 );
lv_obj_set_align( cui_Joint2, LV_ALIGN_CENTER );
lv_arc_set_value(cui_Joint2, 50);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_JOINT2_NUM);
children[UI_COMP_JOINT2_JOINT2] = cui_Joint2;
lv_obj_add_event_cb(cui_Joint2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Joint2, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Joint2_create_hook(cui_Joint2);
return cui_Joint2; 
}

