// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32_S3_7inch_UI

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Action1 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Action2 = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Action3 = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_Action4 = NULL;lv_obj_t *ui_Image4 = NULL;lv_obj_t *ui_Image5 = NULL;lv_obj_t *ui_master = NULL;
// event funtions
void ui_event_Action1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      action1_event( e );
}
}

void ui_event_Action2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      action2_event( e );
}
}

void ui_event_Action3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      action3_event( e );
}
}

void ui_event_Action4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      action4_event( e );
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 777);
lv_obj_set_height( ui_Panel1, 395);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, 21 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Action1 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Action1, 350);
lv_obj_set_height( ui_Action1, 155);
lv_obj_set_x( ui_Action1, -198 );
lv_obj_set_y( ui_Action1, -100 );
lv_obj_set_align( ui_Action1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Action1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Action1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Action1);
lv_img_set_src(ui_Image1, &ui_img_2043791660);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Image1,-100);
lv_img_set_zoom(ui_Image1,100);
lv_obj_set_style_img_recolor(ui_Image1, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Action2 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Action2, 350);
lv_obj_set_height( ui_Action2, 155);
lv_obj_set_x( ui_Action2, 186 );
lv_obj_set_y( ui_Action2, -100 );
lv_obj_set_align( ui_Action2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Action2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Action2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_Action2);
lv_img_set_src(ui_Image2, &ui_img_195482244);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,90);
lv_obj_set_style_img_recolor(ui_Image2, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Action3 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Action3, 350);
lv_obj_set_height( ui_Action3, 155);
lv_obj_set_x( ui_Action3, -198 );
lv_obj_set_y( ui_Action3, 95 );
lv_obj_set_align( ui_Action3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Action3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Action3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image3 = lv_img_create(ui_Action3);
lv_img_set_src(ui_Image3, &ui_img_swap_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image3,250);
lv_obj_set_style_img_recolor(ui_Image3, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Action4 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_Action4, 350);
lv_obj_set_height( ui_Action4, 155);
lv_obj_set_x( ui_Action4, 188 );
lv_obj_set_y( ui_Action4, 95 );
lv_obj_set_align( ui_Action4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Action4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Action4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image4 = lv_img_create(ui_Action4);
lv_img_set_src(ui_Image4, &ui_img_1842574513);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image4,110);
lv_obj_set_style_img_recolor(ui_Image4, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image5, &ui_img_malogo_png);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image5, -5 );
lv_obj_set_y( ui_Image5, 19 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image5,200);
lv_obj_set_style_radius(ui_Image5, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Image5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Image5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_master = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_master, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_master, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_master, 9 );
lv_obj_set_y( ui_master, -211 );
lv_obj_set_align( ui_master, LV_ALIGN_CENTER );
lv_label_set_text(ui_master,"M A S T E R    C O N T R O L");
lv_obj_set_style_text_font(ui_master, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Action1, ui_event_Action1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Action2, ui_event_Action2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Action3, ui_event_Action3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Action4, ui_event_Action4, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Panel1= NULL;
ui_Action1= NULL;
ui_Image1= NULL;
ui_Action2= NULL;
ui_Image2= NULL;
ui_Action3= NULL;
ui_Image3= NULL;
ui_Action4= NULL;
ui_Image4= NULL;
ui_Image5= NULL;
ui_master= NULL;

}
