// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32_S3_7inch_UI

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern void ui_event_Action1( lv_event_t * e);
extern lv_obj_t *ui_Action1;
extern lv_obj_t *ui_Image1;
extern void ui_event_Action2( lv_event_t * e);
extern lv_obj_t *ui_Action2;
extern lv_obj_t *ui_Image2;
extern void ui_event_Action3( lv_event_t * e);
extern lv_obj_t *ui_Action3;
extern lv_obj_t *ui_Image3;
extern void ui_event_Action4( lv_event_t * e);
extern lv_obj_t *ui_Action4;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_master;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

